import { Roboto } from 'next/font/google';

import './global.css';
import Provider from './provider';
import { PrelineScript } from '@ecommerce/lib';

const roboto = Roboto({
  weight: ['300', '400', '500', '700', '900'],
  subsets: ['latin'],
});

export const metadata = {
  title: 'Welcome to admin',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Provider>
          <main className="bg-[#f8fafc]">{children}</main>
        </Provider>
      </body>
      <PrelineScript />
    </html>
  );
}
