import { Roboto } from 'next/font/google';
import { getServerSession } from 'next-auth';

import './global.css';
import AppProvider from './provider';
import { PrelineScript } from 'packages/lib/src';
import { options } from './(auth)/api/auth/[...nextauth]/options';

const roboto = Roboto({
  weight: ['300', '400', '500', '700', '900'],
  subsets: ['latin'],
});

export const metadata = {
  title: 'Welcome to admin',
  description: 'Generated by create-nx-workspace',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const authSession = await getServerSession(options);

  return (
    <html lang="en">
      <body className={roboto.className}>
        <AppProvider session={authSession}>
          <main className="bg-[#f8fafc]">{children}</main>
        </AppProvider>
      </body>
      <PrelineScript />
    </html>
  );
}
