import './global.css';
import Provider from './provider';

export const metadata = {
  title: 'Welcome to admin',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <main className="bg-[#f8fafc]">{children}</main>
        </Provider>
      </body>
    </html>
  );
}
