import './global.css';
import { Roboto } from 'next/font/google';

import { PrelineScript } from '@ecommerce/lib';

import Provider from './provider';

const roboto = Roboto({
  weight: ['300', '400', '500', '700', '900'],
  subsets: ['latin'],
});

export const metadata = {
  title: 'Welcome to user',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Provider>{children}</Provider>
      </body>
      <PrelineScript />
    </html>
  );
}
