import './global.css';
import '@mantine/core/styles.css';
import '@mantine/carousel/styles.css';
import { Roboto } from 'next/font/google';

import { MantineProvider, Container } from '@mantine/core';

import { theme } from 'packages/ui/src';
import Navbar from '../components/navbar';

const roboto = Roboto({
  weight: ['300', '400', '500', '700', '900'],
  subsets: ['latin'],
});

export const metadata = {
  title: 'Welcome to user',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <MantineProvider theme={theme}>
          <Navbar />
          <Container size="xl">{children}</Container>
        </MantineProvider>
      </body>
    </html>
  );
}
